//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The AuthenticationTokenProvider&apos;s required synchronous events have not been registered. 的本地化字符串。
        /// </summary>
        internal static string Exception_AuthenticationTokenDoesNotProvideSyncMethods {
            get {
                return ResourceManager.GetString("Exception_AuthenticationTokenDoesNotProvideSyncMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion delegate must take one parameter. 的本地化字符串。
        /// </summary>
        internal static string Exception_ConversionTakesOneParameter {
            get {
                return ResourceManager.GetString("Exception_ConversionTakesOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cookie key and options are larger than ChunksSize, leaving no room for data. 的本地化字符串。
        /// </summary>
        internal static string Exception_CookieLimitTooSmall {
            get {
                return ResourceManager.GetString("Exception_CookieLimitTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default data protection provider may only be used when the IAppBuilder.Properties contains an appropriate &apos;host.AppName&apos; key. 的本地化字符串。
        /// </summary>
        internal static string Exception_DefaultDpapiRequiresAppNameKey {
            get {
                return ResourceManager.GetString("Exception_DefaultDpapiRequiresAppNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The chunked cookie is incomplete. Only {0} of the expected {1} chunks were found, totaling {2} characters. A client size limit may have been exceeded. 的本地化字符串。
        /// </summary>
        internal static string Exception_ImcompleteChunkedCookie {
            get {
                return ResourceManager.GetString("Exception_ImcompleteChunkedCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not match any known middleware pattern. 的本地化字符串。
        /// </summary>
        internal static string Exception_MiddlewareNotSupported {
            get {
                return ResourceManager.GetString("Exception_MiddlewareNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A default value for SignInAsAuthenticationType was not found in IAppBuilder Properties. This can happen if your authentication middleware are added in the wrong order, or if one is missing. 的本地化字符串。
        /// </summary>
        internal static string Exception_MissingDefaultSignInAsAuthenticationType {
            get {
                return ResourceManager.GetString("Exception_MissingDefaultSignInAsAuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The OWIN key &apos;server.OnSendingHeaders&apos; is not available for this request. 的本地化字符串。
        /// </summary>
        internal static string Exception_MissingOnSendingHeaders {
            get {
                return ResourceManager.GetString("Exception_MissingOnSendingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The class &apos;{0}&apos; does not have a constructor taking {1} arguments. 的本地化字符串。
        /// </summary>
        internal static string Exception_NoConstructorFound {
            get {
                return ResourceManager.GetString("Exception_NoConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No conversion available between {0} and {1}. 的本地化字符串。
        /// </summary>
        internal static string Exception_NoConversionExists {
            get {
                return ResourceManager.GetString("Exception_NoConversionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path must not end with a &apos;/&apos; 的本地化字符串。
        /// </summary>
        internal static string Exception_PathMustNotEndWithSlash {
            get {
                return ResourceManager.GetString("Exception_PathMustNotEndWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path must start with a &apos;/&apos; followed by one or more characters. 的本地化字符串。
        /// </summary>
        internal static string Exception_PathMustStartWithSlash {
            get {
                return ResourceManager.GetString("Exception_PathMustStartWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path is required 的本地化字符串。
        /// </summary>
        internal static string Exception_PathRequired {
            get {
                return ResourceManager.GetString("Exception_PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The query string must start with a &apos;?&apos; unless null or empty. 的本地化字符串。
        /// </summary>
        internal static string Exception_QueryStringMustStartWithDelimiter {
            get {
                return ResourceManager.GetString("Exception_QueryStringMustStartWithDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The state passed to UnhookAuthentication may only be the return value from HookAuthentication. 的本地化字符串。
        /// </summary>
        internal static string Exception_UnhookAuthenticationStateType {
            get {
                return ResourceManager.GetString("Exception_UnhookAuthenticationStateType", resourceCulture);
            }
        }
    }
}
