// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CellStatMysql_201605111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CellStatMysql_201605111));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111320562_CellStatMysql_201605111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
