// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_NearestLteNeighborCell_Add_TotalTimes_20160111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_NearestLteNeighborCell_Add_TotalTimes_20160111));
        
        string IMigrationMetadata.Id
        {
            get { return "201601110355116_Update_NearestLteNeighborCell_Add_TotalTimes_20160111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
