// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Parameters_Add_IsInUse_Flag_20160106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parameters_Add_IsInUse_Flag_20160106));
        
        string IMigrationMetadata.Id
        {
            get { return "201601060923310_Parameters_Add_IsInUse_Flag_20160106"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
