//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Core.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools</string>
  <string>C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools</string>
  <string>c:\Program Files\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools</string>
  <string>C:\Program Files\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools</string>
  <string>C:\Program Files\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools</string>
  <string>C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools</string>
  <string>C:\Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools</string>
  <string>C:\Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools</string>
  <string>C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0\bin</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PeVerifyProbingPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PeVerifyProbingPaths"]));
            }
            set {
                this["PeVerifyProbingPaths"] = value;
            }
        }
    }
}
