//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.Identity.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown failure has occured. 的本地化字符串。
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email &apos;{0}&apos; is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name {0} is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name {0} is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A user with that external login already exists. 的本地化字符串。
        /// </summary>
        internal static string ExternalLoginExists {
            get {
                return ResourceManager.GetString("ExternalLoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model backing the &apos;ApplicationDbContext&apos; context has changed since the database was created. This could have happened because the model used by ASP.NET Identity Framework has changed or the model being used in your application has changed. To resolve this issue, you need to update your database. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=301867).  Before you update your database using Code First Migrations, please disable the schema consistency ch [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IdentityV1SchemaError {
            get {
                return ResourceManager.GetString("IdentityV1SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid token. 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name {0} is invalid, can only contain letters or digits. 的本地化字符串。
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lockout is not enabled for this user. 的本地化字符串。
        /// </summary>
        internal static string LockoutNotEnabled {
            get {
                return ResourceManager.GetString("LockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No IUserTokenProvider is registered. 的本地化字符串。
        /// </summary>
        internal static string NoTokenProvider {
            get {
                return ResourceManager.GetString("NoTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No IUserTwoFactorProvider for &apos;{0}&apos; is registered. 的本地化字符串。
        /// </summary>
        internal static string NoTwoFactorProvider {
            get {
                return ResourceManager.GetString("NoTwoFactorProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect password. 的本地化字符串。
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequireDigit {
            get {
                return ResourceManager.GetString("PasswordRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequireLower {
            get {
                return ResourceManager.GetString("PasswordRequireLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one non letter or digit character. 的本地化字符串。
        /// </summary>
        internal static string PasswordRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("PasswordRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequireUpper {
            get {
                return ResourceManager.GetString("PasswordRequireUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must be at least {0} characters. 的本地化字符串。
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string PropertyTooShort {
            get {
                return ResourceManager.GetString("PropertyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role {0} already exists. 的本地化字符串。
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IQueryableRoleStore&lt;TRole&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIQueryableRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IQueryableUserStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIQueryableUserStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserClaimStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIUserClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserConfirmationStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserConfirmationStore {
            get {
                return ResourceManager.GetString("StoreNotIUserConfirmationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserEmailStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserEmailStore {
            get {
                return ResourceManager.GetString("StoreNotIUserEmailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserLockoutStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserLockoutStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLockoutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserLoginStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserLoginStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLoginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserPasswordStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserPasswordStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPasswordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserPhoneNumberStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserPhoneNumberStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPhoneNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserRoleStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIUserRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserSecurityStampStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotIUserSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserTwoFactorStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserTwoFactorStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already has a password set. 的本地化字符串。
        /// </summary>
        internal static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already in role. 的本地化字符串。
        /// </summary>
        internal static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserId not found. 的本地化字符串。
        /// </summary>
        internal static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is not in role. 的本地化字符串。
        /// </summary>
        internal static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
    }
}
