// <auto-generated />
namespace LtePlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHometown20151101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHometown20151101));
        
        string IMigrationMetadata.Id
        {
            get { return "201511010036147_AddHometown20151101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
